[w]
width = 500
height = 500
size_inc = 50.0

[f]
min = [
    -4,
    -4,
]
max = [
    4,
    4,
]
max_it = 31
it_inc = 16
move_inc_rate = 0.04
zoom_factor = 1.25
fractal_type = 'Mandelbrot'
color_scheme = 'Silver'
