name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build compute
      run: pushd compute && cargo build --verbose && popd
    - name: Build frontend
      run: pushd frontend && cargo build --verbose && popd
